<script>
import Pagination from 'vuejs-paginate';
import constant from 'lodash/constant';

const ITEMS_PER_PAGE = 3;

export default {
  components: { Pagination },
  props: {
    hotels: {
      type: Array,
      required: true,
    },
    isLoading: {
      type: Boolean,
      required: true,
    },
  },
  data: () => ({ page: 1 }),
  computed: {
    currentChunk() {
      const begin = (this.page - 1) * this.ITEMS_PER_PAGE;
      return this.hotels.slice(begin, begin + this.ITEMS_PER_PAGE);
    },
    pagesTotal() {
      return Math.ceil(this.hotels.length / this.ITEMS_PER_PAGE);
    },
    ITEMS_PER_PAGE: constant(ITEMS_PER_PAGE),
    paginationClasses: () => {
      const itemKinds = ['page', 'prev', 'next'];
      return {
        ...itemKinds.reduce(
          (acc, cur) => ({ ...acc, [`${cur}Class`]: 'page-item', [`${cur}LinkClass`]: 'page-link' }),
          {},
        ),
        containerClass: 'pagination',
      };
    },
  },
  watch: {
    hotels() {
      this.checkPageNumber();
    },
  },
  methods: {
    checkPageNumber() {
      if (this.page > this.pagesTotal) {
        this.page = this.pagesTotal;
      }
      if (this.page < 1) {
        this.page = 1;
      }
    },
  },
};
</script>

<template>
  <div>
    <div v-if="isLoading" class="d-flex justify-content-center">
      <div class="preloader">
        <div class="preloader-inner">
          <div />
        </div>
      </div>
    </div>
    <div v-else-if="hotels.length !== 0">
      <table class="table table-responsive-sm">
        <thead>
          <tr>
            <th>Название</th>
            <th>Описание</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="hotel of currentChunk" :key="hotel.name">
            <td>{{ hotel.name }}</td>
            <td>
              <div class="row">
                <div class="col">
                  {{ hotel.description }}
                </div>
                <div class="col-auto">
                  <button class="btn btn-primary" type="button">Забронировать</button>
                </div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
      <pagination
        v-if="pagesTotal > 1"
        v-model="page"
        :page-count="pagesTotal"
        :page-range="ITEMS_PER_PAGE"
        :margin-pages="2"
        prev-text="<<"
        next-text=">>"
        v-bind="paginationClasses"
      />
    </div>
    <div v-else class="border rounded text-center bg-light py-3 w-100">Записей не найдено</div>
  </div>
</template>

<style lang="sass" scoped>
@keyframes preloader
  0%
    transform: rotate(0deg)
  50%
    transform: rotate(180deg)
  100%
    transform: rotate(360deg)

.preloader
  width: 200px
  height: 200px
  display: inline-block
  overflow: hidden
  background: none

.preloader-inner
  width: 100%
  height: 100%
  position: relative
  transform: translateZ(0) scale(1)
  backface-visibility: hidden
  transform-origin: 0 0 /* see note above */

  div
    position: absolute
    animation: preloader 1s linear infinite
    width: 128px
    height: 128px
    top: 36px
    left: 36px
    border-radius: 50%
    box-shadow: 0 4px 0 0 #3163ff
    transform-origin: 64px 66px
    box-sizing: content-box
/* generated by https://loading.io/ */
</style>
